### PR TITLE
Change package name from Decanter to Backdrop Decanter

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Changes NPM Package Names to avoid confusion in the NPM space

### CODE REVIEW

**Comment by sherakama** [comment]
@borisay, please have a review.

**Review by borisay — APPROVED** [review]
@sherakama, thank you!

**Review by borisay — APPROVED** [review]

**Review by borisay — APPROVED** [review]

**Review by borisay — APPROVED** [review]

**Comment by sherakama** [comment]
Thanks for approving but I don't have permission to merge so you'll have to do that.

**Comment by borisay** [comment]
@sherakama, thank you, very helpful!

**Pull request merged**
